[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.2.0"
update_changelog_on_bump = true
major_version_zero = true
breaking_change_exclamation_in_title = true
gpg_sign = true
changelog_pattern = "^(feat|fix|refactor|perf|docs|style|test|build|ci)"


[tool.commitizen.change_type_map]
feat     = "Feat"
fix      = "Bug Fixes"
refactor = "Refactor"
perf     = "Performance"
docs     = "Docs"
style    = "Style"
test     = "Tests"
build    = "Build System"
ci       = "CI"
