name: PR Specs

on:
  pull_request:
    branches:
      - main
jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: oprypin/install-crystal@d8ef131ecec0352ce0e39b81b0a6d95def58fe2f # v1
        with:
          crystal: "1.20.0"

      - name: Install shards
        # skip ameba postinstall which isn't takes time to compile and isn't used for specs anyways
        run: shards install --skip-postinstall

      - name: Run specs
        run: crystal spec
